feat(services): add headertitle
TimBuilding/Elysseum pull request #5
Opened 2024-05-04 15:48 UTC by xdjeremy

2024-05-04 15:48 UTC, xdjeremy commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/TimBuilding/Elysseum/5?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#5** <a href="https://app.graphite.dev/github/pr/TimBuilding/Elysseum/5?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#4** <a href="https://app.graphite.dev/github/pr/TimBuilding/Elysseum/4?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#3** <a href="https://app.graphite.dev/github/pr/TimBuilding/Elysseum/3?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1** <a href="https://app.graphite.dev/github/pr/TimBuilding/Elysseum/1?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @xdjeremy and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-05-04 19:14 UTC, tamrivera05 requested changes
clean your code. remove your comments hmp

2024-05-05 02:27 UTC, xdjeremy commented
> clean your code. remove your comments hmp
> 
> 

k na

2024-05-05 02:36 UTC, tamrivera05 approved these changes

2024-05-05 02:43 UTC, merged