feat: Contact Form for Contact Us page and Input component
TimBuilding/Elysseum pull request #7
Opened 2024-05-04 19:09 UTC by tamrivera05

2024-05-04 19:09 UTC, tamrivera05 commented
* **#7** <a href="https://app.graphite.dev/github/pr/TimBuilding/Elysseum/7?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @tamrivera05 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-05-04 19:53 UTC, xdjeremy requested changes

2024-05-04 19:53 UTC, xdjeremy commented on src/pages/contact.astro
> +const contacts: ContactFormProps[] = [
Use array instead, if title lang naman
```javascript
const contacts = ['Name', 'Phone Number', 'etc'] 
```

2024-05-05 11:16 UTC, tamrivera05 commented on src/pages/contact.astro
> +const contacts: ContactFormProps[] = [
oki po mwa

2024-05-05 12:19 UTC, xdjeremy approved these changes
[![cool](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/default-memes/cool.gif)](https://app.graphite.dev//settings/meme-library?org=TimBuilding)

2024-05-05 12:28 UTC, merged